// <auto-generated />
using System;
using AttendAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726173403_AddSecureAttendanceCheckIn")]
    partial class AddSecureAttendanceCheckIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendAI.Domain.Academic.AttendanceAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AllowedRadiusMeters")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("BrowserAccuracyMeters")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("ChallengeTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("DistanceMeters")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid?>("FaceVerificationAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailureReason")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("LectureSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LocationOutcome")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumAcceptedAccuracyMeters")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessingDurationMilliseconds")
                        .HasColumnType("int");

                    b.Property<string>("SafeDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FaceVerificationAttemptId")
                        .HasDatabaseName("IX_AttendanceAttempts_FaceVerificationAttemptId");

                    b.HasIndex("LectureSessionId", "AttemptedAtUtc")
                        .HasDatabaseName("IX_AttendanceAttempts_Session_AttemptedAtUtc");

                    b.HasIndex("StudentId", "AttemptedAtUtc")
                        .HasDatabaseName("IX_AttendanceAttempts_Student_AttemptedAtUtc");

                    b.HasIndex("StudentId", "LectureSessionId", "IdempotencyKeyHash")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceAttempts_Student_Session_Idempotency");

                    b.ToTable("AttendanceAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceAttempts_AllowedRadiusMeters", "[AllowedRadiusMeters] IS NULL OR [AllowedRadiusMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceAttempts_BrowserAccuracyMeters", "[BrowserAccuracyMeters] IS NULL OR [BrowserAccuracyMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceAttempts_DistanceMeters", "[DistanceMeters] IS NULL OR [DistanceMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceAttempts_MaximumAcceptedAccuracyMeters", "[MaximumAcceptedAccuracyMeters] IS NULL OR [MaximumAcceptedAccuracyMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceAttempts_ProcessingDuration", "[ProcessingDurationMilliseconds] IS NULL OR [ProcessingDurationMilliseconds] >= 0");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.AttendanceChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ConsumedByAttendanceAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LectureSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LectureSessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceChallenges_TokenHash");

                    b.HasIndex("StudentId", "LectureSessionId", "ExpiresAtUtc")
                        .HasDatabaseName("IX_AttendanceChallenges_Student_Session_Expires");

                    b.ToTable("AttendanceChallenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceChallenges_ExpiresAfterIssued", "[ExpiresAtUtc] > [IssuedAtUtc]");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowedRadiusMeters")
                        .HasColumnType("int");

                    b.Property<Guid>("AttendanceAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BrowserAccuracyMeters")
                        .HasColumnType("decimal(9,3)");

                    b.Property<DateTimeOffset>("CheckedInAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DistanceMeters")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("FaceVerificationAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LectureSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaximumAcceptedAccuracyMeters")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceAttemptId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRecords_AttendanceAttemptId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("FaceVerificationAttemptId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRecords_FaceVerificationAttemptId");

                    b.HasIndex("StudentId");

                    b.HasIndex("LectureSessionId", "Status")
                        .HasDatabaseName("IX_AttendanceRecords_Session_Status");

                    b.HasIndex("LectureSessionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRecords_Session_Student");

                    b.ToTable("AttendanceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecords_AllowedRadiusMeters", "[AllowedRadiusMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_BrowserAccuracyMeters", "[BrowserAccuracyMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_DistanceMeters", "[DistanceMeters] >= 0");

                            t.HasCheckConstraint("CK_AttendanceRecords_MaximumAcceptedAccuracyMeters", "[MaximumAcceptedAccuracyMeters] >= 0");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.BiometricConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AcceptedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConsentTextHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("WithdrawnAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WithdrawnByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_BiometricConsents_StudentId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("BiometricConsents", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNameArabic")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("BuildingNameEnglish")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("BuildingNameEnglish", "RoomNumber");

                    b.ToTable("Classrooms", t =>
                        {
                            t.HasCheckConstraint("CK_Classrooms_Capacity", "[Capacity] > 0");

                            t.HasCheckConstraint("CK_Classrooms_CoordinatePair", "(([Latitude] IS NULL AND [Longitude] IS NULL) OR ([Latitude] IS NOT NULL AND [Longitude] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Classrooms_Latitude", "[Latitude] IS NULL OR (CAST([Latitude] AS REAL) BETWEEN -90 AND 90)");

                            t.HasCheckConstraint("CK_Classrooms_Longitude", "[Longitude] IS NULL OR (CAST([Longitude] AS REAL) BETWEEN -180 AND 180)");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionArabic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEnglish")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "IsActive");

                    b.ToTable("Courses", t =>
                        {
                            t.HasCheckConstraint("CK_Courses_CreditHours", "[CreditHours] BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescriptionArabic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEnglish")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.FaceEnrollmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BiometricConsentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FaceTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SafeDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BiometricConsentId")
                        .HasDatabaseName("IX_FaceEnrollmentEvents_BiometricConsentId");

                    b.HasIndex("FaceTemplateId")
                        .HasDatabaseName("IX_FaceEnrollmentEvents_FaceTemplateId");

                    b.HasIndex("StudentId", "OccurredAtUtc")
                        .HasDatabaseName("IX_FaceEnrollmentEvents_StudentId_OccurredAtUtc");

                    b.ToTable("FaceEnrollmentEvents", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.FaceVerificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<int?>("DetectedFaceCount")
                        .HasColumnType("int");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("FaceTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("int");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessingDurationMilliseconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("SafeDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("ScoreMetric")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateFormatVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VerificationPurpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaceTemplateId")
                        .HasDatabaseName("IX_FaceVerificationAttempts_FaceTemplateId");

                    b.HasIndex("Outcome", "AttemptedAtUtc")
                        .HasDatabaseName("IX_FaceVerificationAttempts_Outcome_AttemptedAtUtc");

                    b.HasIndex("StudentId", "AttemptedAtUtc")
                        .HasDatabaseName("IX_FaceVerificationAttempts_StudentId_AttemptedAtUtc");

                    b.HasIndex("StudentId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_FaceVerificationAttempts_StudentId_ClientRequestId")
                        .HasFilter("[ClientRequestId] <> ''");

                    b.ToTable("FaceVerificationAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_FaceVerificationAttempts_DetectedFaceCount", "[DetectedFaceCount] IS NULL OR [DetectedFaceCount] >= 0");

                            t.HasCheckConstraint("CK_FaceVerificationAttempts_ImageHeight", "[ImageHeight] IS NULL OR [ImageHeight] >= 0");

                            t.HasCheckConstraint("CK_FaceVerificationAttempts_ImageWidth", "[ImageWidth] IS NULL OR [ImageWidth] >= 0");

                            t.HasCheckConstraint("CK_FaceVerificationAttempts_ProcessingDuration", "[ProcessingDurationMilliseconds] IS NULL OR [ProcessingDurationMilliseconds] >= 0");

                            t.HasCheckConstraint("CK_FaceVerificationAttempts_QualityScore", "[QualityScore] IS NULL OR ([QualityScore] >= 0 AND [QualityScore] <= 1)");

                            t.HasCheckConstraint("CK_FaceVerificationAttempts_Score", "[Score] IS NULL OR [Score] >= 0");

                            t.HasCheckConstraint("CK_FaceVerificationAttempts_Threshold", "[Threshold] >= 0");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "AcademicTitle", "IsActive");

                    b.ToTable("Instructors", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.InstructorAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId", "SectionId")
                        .IsUnique();

                    b.HasIndex("SectionId", "IsPrimary", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1 AND [IsActive] = 1");

                    b.ToTable("InstructorAssignments", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DefaultAllowedRadiusMeters")
                        .HasColumnType("int");

                    b.Property<int>("DefaultLateThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId", "DayOfWeek", "IsActive", "EffectiveFrom", "EffectiveTo", "StartTime", "EndTime");

                    b.HasIndex("InstructorId", "DayOfWeek", "IsActive", "EffectiveFrom", "EffectiveTo", "StartTime", "EndTime");

                    b.HasIndex("SectionId", "DayOfWeek", "IsActive", "EffectiveFrom", "EffectiveTo", "StartTime", "EndTime");

                    b.ToTable("LectureSchedules", t =>
                        {
                            t.HasCheckConstraint("CK_LectureSchedules_AllowedRadius", "[DefaultAllowedRadiusMeters] >= 0");

                            t.HasCheckConstraint("CK_LectureSchedules_EffectiveRange", "[EffectiveFrom] <= [EffectiveTo]");

                            t.HasCheckConstraint("CK_LectureSchedules_LateThreshold", "[DefaultLateThresholdMinutes] >= 0");

                            t.HasCheckConstraint("CK_LectureSchedules_TimeRange", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ActualEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ActualStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AllowedRadiusMeters")
                        .HasColumnType("int");

                    b.Property<bool>("AttendanceCheckInEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("AttendanceLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("AttendanceLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EndReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EndedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("FaceVerificationRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LateThresholdMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("LectureScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LocationVerificationRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaximumAcceptedAccuracyMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(75);

                    b.Property<string>("ProtectedSessionCode")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("ScheduledEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SessionCodeExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SessionCodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SessionCodeVersion")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("StartedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SessionCodeExpiresAtUtc");

                    b.HasIndex("ClassroomId", "Status");

                    b.HasIndex("InstructorId", "Status");

                    b.HasIndex("LectureScheduleId", "SessionDate")
                        .IsUnique();

                    b.HasIndex("SectionId", "Status");

                    b.ToTable("LectureSessions", t =>
                        {
                            t.HasCheckConstraint("CK_LectureSessions_AllowedRadius", "[AllowedRadiusMeters] >= 0");

                            t.HasCheckConstraint("CK_LectureSessions_AttendanceCoordinatePair", "([AttendanceLatitude] IS NULL AND [AttendanceLongitude] IS NULL) OR ([AttendanceLatitude] IS NOT NULL AND [AttendanceLongitude] IS NOT NULL)");

                            t.HasCheckConstraint("CK_LectureSessions_AttendanceLatitude", "[AttendanceLatitude] IS NULL OR (CAST([AttendanceLatitude] AS REAL) BETWEEN -90 AND 90)");

                            t.HasCheckConstraint("CK_LectureSessions_AttendanceLongitude", "[AttendanceLongitude] IS NULL OR (CAST([AttendanceLongitude] AS REAL) BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_LectureSessions_LateThreshold", "[LateThresholdMinutes] >= 0");

                            t.HasCheckConstraint("CK_LectureSessions_MaximumAcceptedAccuracyMeters", "[MaximumAcceptedAccuracyMeters] > 0");

                            t.HasCheckConstraint("CK_LectureSessions_ScheduledRange", "[ScheduledStartUtc] < [ScheduledEndUtc]");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid>("LectureSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("SafeDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LectureSessionId", "OccurredAtUtc");

                    b.ToTable("LectureSessionEvents");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "AcademicYear", "Semester", "IsActive");

                    b.HasIndex("CourseId", "AcademicYear", "Semester", "SectionNumber")
                        .IsUnique();

                    b.ToTable("Sections", t =>
                        {
                            t.HasCheckConstraint("CK_Sections_Capacity", "[Capacity] > 0");
                        });
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicLevel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "AcademicLevel", "IsActive");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EnrollmentStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "SectionId")
                        .IsUnique();

                    b.HasIndex("SectionId", "EnrollmentStatus", "IsActive");

                    b.ToTable("StudentEnrollments", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.StudentFaceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BiometricConsentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CaptureCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("int");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("ProtectedTemplate")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("QualityScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<bool>("RequiresReEnrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevokedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TemplateFormatVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BiometricConsentId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentFaceTemplates_StudentId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("TemplateFingerprint")
                        .HasDatabaseName("IX_StudentFaceTemplates_TemplateFingerprint");

                    b.HasIndex("StudentId", "TemplateVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentFaceTemplates_StudentId_TemplateVersion");

                    b.HasIndex("StudentId", "IsActive", "RequiresReEnrollment")
                        .HasDatabaseName("IX_StudentFaceTemplates_Status");

                    b.ToTable("StudentFaceTemplates", t =>
                        {
                            t.HasCheckConstraint("CK_StudentFaceTemplates_CaptureCount", "[CaptureCount] > 0");

                            t.HasCheckConstraint("CK_StudentFaceTemplates_EmbeddingDimension", "[EmbeddingDimension] > 0");

                            t.HasCheckConstraint("CK_StudentFaceTemplates_QualityScore", "[QualityScore] >= 0 AND [QualityScore] <= 1");

                            t.HasCheckConstraint("CK_StudentFaceTemplates_TemplateVersion", "[TemplateVersion] > 0");
                        });
                });

            modelBuilder.Entity("AttendAI.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.AttendanceAttempt", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.FaceVerificationAttempt", "FaceVerificationAttempt")
                        .WithMany()
                        .HasForeignKey("FaceVerificationAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendAI.Domain.Academic.LectureSession", "LectureSession")
                        .WithMany()
                        .HasForeignKey("LectureSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaceVerificationAttempt");

                    b.Navigation("LectureSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.AttendanceChallenge", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.LectureSession", "LectureSession")
                        .WithMany()
                        .HasForeignKey("LectureSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LectureSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.AttendanceRecord", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.AttendanceAttempt", "AttendanceAttempt")
                        .WithMany()
                        .HasForeignKey("AttendanceAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.FaceVerificationAttempt", "FaceVerificationAttempt")
                        .WithMany()
                        .HasForeignKey("FaceVerificationAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.LectureSession", "LectureSession")
                        .WithMany()
                        .HasForeignKey("LectureSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceAttempt");

                    b.Navigation("Classroom");

                    b.Navigation("FaceVerificationAttempt");

                    b.Navigation("LectureSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.BiometricConsent", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Course", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.FaceEnrollmentEvent", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.BiometricConsent", "BiometricConsent")
                        .WithMany()
                        .HasForeignKey("BiometricConsentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendAI.Domain.Academic.StudentFaceTemplate", "FaceTemplate")
                        .WithMany()
                        .HasForeignKey("FaceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BiometricConsent");

                    b.Navigation("FaceTemplate");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.FaceVerificationAttempt", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.StudentFaceTemplate", "FaceTemplate")
                        .WithMany()
                        .HasForeignKey("FaceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaceTemplate");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Instructor", b =>
                {
                    b.HasOne("AttendAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AttendAI.Domain.Academic.Instructor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.InstructorAssignment", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Instructor", "Instructor")
                        .WithMany("Assignments")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Section", "Section")
                        .WithMany("InstructorAssignments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSchedule", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Instructor");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSession", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.LectureSchedule", "LectureSchedule")
                        .WithMany("Sessions")
                        .HasForeignKey("LectureScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Instructor");

                    b.Navigation("LectureSchedule");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSessionEvent", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.LectureSession", "LectureSession")
                        .WithMany("Events")
                        .HasForeignKey("LectureSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LectureSession");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Section", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Student", b =>
                {
                    b.HasOne("AttendAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("AttendAI.Domain.Academic.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.StudentEnrollment", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.Section", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.StudentFaceTemplate", b =>
                {
                    b.HasOne("AttendAI.Domain.Academic.BiometricConsent", "BiometricConsent")
                        .WithMany()
                        .HasForeignKey("BiometricConsentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendAI.Domain.Academic.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BiometricConsent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AttendAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AttendAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AttendAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Instructor", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSchedule", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.LectureSession", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Section", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("InstructorAssignments");
                });

            modelBuilder.Entity("AttendAI.Domain.Academic.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
